wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1659797002
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 3
      - 8
      - 13
      - 16
      4: 3.9.12
      5: 0.12.16
      8:
      - 1
      - 4
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 75
learning_rate:
  desc: null
  value: 0.0008
